### ISSUE TITLE
Broken link on Canvas page

### ISSUE THREAD

**Issue by johnbcoughlin** [trogdoncourses/amath-586-2020#1]
This link to the team page is broken:

<img width="492" alt="Screen Shot 2020-04-01 at 6 30 26 PM" src="https://user-images.githubusercontent.com/2209490/78201644-ecf17000-7446-11ea-9d06-68ff1caeb1af.png">

**Comment by kels271828** [comment]
I think you may need to accept the invitation to the Trogdon Courses organization to be able to use the link. Right now it looks like your invitation is pending.

**Comment by johnbcoughlin** [comment]
Sorry Kelsey, I got an email about that but I think the link just took me to the repo that I had already created... Can you reinvite? It says it was 8 days ago and the invite is valid for 7.

**Comment by johnbcoughlin** [comment]
Scratch that, it looks like I did successfully accept the invitation, and now `Settings > Organizations` lists me as an "outside collaborator" on `trogdoncourses`. The link is still broken.  I'm worried that this may be related to the fact my github account is tied to my personal email, not my uw.edu email?

**Comment by kels271828** [comment]
Yeah, it looks like you are listed as a member now. Are you able to set up your homework repositories and access the discussion board: https://github.com/orgs/trogdoncourses/teams/586-students/discussions ?
