### ISSUE TITLE
Code says leap frog is not consistent

### ISSUE THREAD

**Issue by Nicholaswogan** [trogdoncourses/amath-586-2020#2]
https://github.com/trogdoncourses/amath-586-2020/blob/cf73b9932edbcde4510054bf8df465aea18303e5/notebooks/AbsoluteStabilityRegions.jl#L106

The code says leap frog is not consistent, but it is? What is wrong here.

**Comment by tomtrogdon** [comment]
Something is wrong here.  This is not actually leapfrog.  What is wrong?

**Comment by Nicholaswogan** [comment]
Oh ok ya the alpha_j should be [1,0,-1]

**Comment by tomtrogdon** [comment]
Yep.  I'll push a change soon.
