### ISSUE TITLE
to_a method preserve spatial dimension  

### ISSUE THREAD

**Issue by asaadaldien** [trogdoncourses/amath-586-2020#3]
I think we need to preserve spatial dimension here:
https://github.com/trogdoncourses/amath-586-2020/blob/9f4cadb03ef03cf1de609ed5a0b8d2d96d2a9fdb/midterm/midterm.tex#L147
needs to be
```
 to_a = (p,q) -> .5*exp.(-(q[2:end, :]-q[1:end-1, :])/2) 
```

**Comment by tomtrogdon** [comment]
You can of course modify as you need.  For my code p,q are both vectors, and a is the off-diagonal which has one fewer entry than p,q,b.

**Comment by asaadaldien** [comment]
Got it, Thank you!
